# Generated by Django 5.2.16 on 2026-07-29 11:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='titlu')),
                ('media_type', models.CharField(choices=[('image', 'Imagine'), ('video', 'Videoclip')], max_length=10, verbose_name='tip')),
                ('r2_object_key', models.CharField(max_length=500, unique=True, verbose_name='cheie obiect R2')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nume fișier original')),
                ('mime_type', models.CharField(max_length=100, verbose_name='tip MIME')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='dimensiune')),
                ('checksum', models.CharField(blank=True, max_length=128, null=True, verbose_name='checksum')),
                ('is_active', models.BooleanField(default=True, verbose_name='activ')),
            ],
            options={
                'verbose_name': 'material media',
                'verbose_name_plural': 'materiale media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nume')),
                ('description', models.TextField(blank=True, verbose_name='descriere')),
                ('is_active', models.BooleanField(default=True, verbose_name='activ')),
                ('published_version', models.PositiveIntegerField(default=0, verbose_name='versiune publicată')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicat la')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlisturi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nume')),
                ('device_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='cheie dispozitiv')),
                ('is_active', models.BooleanField(default=True, verbose_name='activ')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='văzut ultima dată')),
                ('assigned_playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='kiosk.playlist', verbose_name='playlist asociat')),
            ],
            options={
                'verbose_name': 'dispozitiv',
                'verbose_name_plural': 'dispozitive',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshot', to='kiosk.playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image_duration_seconds', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='playlist_items', to='kiosk.mediaasset')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kiosk.playlist')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('playlist', 'position'), name='unique_draft_position')],
            },
        ),
        migrations.CreateModel(
            name='PublishedPlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('image_duration_seconds', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Imagine'), ('video', 'Videoclip')], max_length=10)),
                ('r2_object_key', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_items', to='kiosk.mediaasset')),
                ('published_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kiosk.publishedplaylist')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('published_playlist', 'position'), name='unique_published_position')],
            },
        ),
    ]
