# Generated by Django 5.2.16 on 2026-07-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedplaylist',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
