# Generated by Django 5.2.16 on 2026-07-29 11:50

import kiosk.models
from django.db import migrations, models


def copy_legacy_paths_forward(apps, schema_editor):
    MediaAsset = apps.get_model("kiosk", "MediaAsset")
    PublishedPlaylistItem = apps.get_model("kiosk", "PublishedPlaylistItem")
    for asset in MediaAsset.objects.exclude(r2_object_key=""):
        asset.file = asset.r2_object_key
        asset.save(update_fields=["file"])
    for item in PublishedPlaylistItem.objects.exclude(r2_object_key=""):
        item.file_name = item.r2_object_key
        item.save(update_fields=["file_name"])


def copy_legacy_paths_backward(apps, schema_editor):
    MediaAsset = apps.get_model("kiosk", "MediaAsset")
    PublishedPlaylistItem = apps.get_model("kiosk", "PublishedPlaylistItem")
    for asset in MediaAsset.objects.exclude(file=""):
        asset.r2_object_key = str(asset.file)
        asset.save(update_fields=["r2_object_key"])
    for item in PublishedPlaylistItem.objects.exclude(file_name=""):
        item.r2_object_key = item.file_name
        item.save(update_fields=["r2_object_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_backfill_published_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, default='', max_length=500, upload_to=kiosk.models.media_upload_path, verbose_name='fișier'),
        ),
        migrations.AddField(
            model_name='publishedplaylistitem',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(copy_legacy_paths_forward, copy_legacy_paths_backward),
        migrations.RemoveField(
            model_name='mediaasset',
            name='r2_object_key',
        ),
        migrations.RemoveField(
            model_name='publishedplaylistitem',
            name='r2_object_key',
        ),
    ]
