# Generated by Django 5.2.16 on 2026-07-30 07:51

import kiosk.models
from django.db import migrations, models


def backfill_existing_media(apps, schema_editor):
    MediaAsset = apps.get_model('kiosk', 'MediaAsset')
    MediaProcessingLock = apps.get_model('kiosk', 'MediaProcessingLock')
    MediaProcessingLock.objects.get_or_create(singleton=1)
    for asset in MediaAsset.objects.all().iterator():
        asset.processing_status = 'ready'
        asset.processing_progress = 100
        asset.original_file_size = asset.file_size
        asset.final_file_size = asset.file_size
        asset.save(update_fields=[
            'processing_status', 'processing_progress', 'original_file_size', 'final_file_size'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_remove_mediaasset_r2_object_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaProcessingLock',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('worker_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'blocare procesare media',
                'verbose_name_plural': 'blocări procesare media',
            },
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='audio_codec',
            field=models.CharField(blank=True, max_length=64, verbose_name='codec audio'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True, verbose_name='durată secunde'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='final_file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='dimensiune finală'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='original_file_size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='dimensiune originală'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='încercări procesare'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_error',
            field=models.CharField(blank=True, max_length=500, verbose_name='eroare procesare'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='procesare finalizată'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_output',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='output temporar'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_progress',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='progres procesare'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='procesare începută'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='processing_status',
            field=models.CharField(choices=[('queued', 'În așteptare'), ('processing', 'Se optimizează'), ('ready', 'Pregătit'), ('failed', 'Procesarea a eșuat')], db_index=True, default='ready', max_length=20, verbose_name='status procesare'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='introdus în coadă'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='source_file',
            field=models.FileField(blank=True, default='', max_length=500, upload_to=kiosk.models.video_source_upload_path, verbose_name='sursă temporară'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='video_codec',
            field=models.CharField(blank=True, max_length=64, verbose_name='codec video'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='video_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='înălțime video'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='video_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='lățime video'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='worker_pid',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='PID worker'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='worker_token',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='identificator worker'),
        ),
        migrations.RunPython(backfill_existing_media, migrations.RunPython.noop),
    ]
